version: "3.7"

services:

    backend:
        build: ./backend
        environment:
            PYTHONUNBUFFERED: 1
            BASE_URL: "http://localhost:5001"
            
        volumes:
            - ./backend:/app
            - ./db:/db
        restart: unless-stopped
        ports:
            - "5001:5000"


    db_update_service:
        build: ./db_update_service
        environment:
          PYTHONUNBUFFERED: 1
        volumes:
          - ./db_update_service:/app
        restart: unless-stopped
        depends_on:
          - backend

    db_backup_service:
        build: ./db_backup_service
        restart: unless-stopped
        volumes:
            - ./db_backup_service:/app
            - ./db:/db

    frontend:
        build: ./frontend
        command: npm run serve -- --port 8080
        volumes:
            - ./frontend:/frontend
        
        environment: 
            - VUE_APP_URL=http://localhost:5001 
        depends_on:
            - backend
        ports:
            - "8080:8080"
