version: "3.7"

services:

    # db:
    #     image: mysql:5.7
    #     restart: always
    #     command: --disable-partition-engine-check
    #     environment:
    #         MYSQL_DATABASE: 'db'
    #         # So you don't have to use root, but you can if you like
    #         MYSQL_USER: 'adrian'
    #         # You can use whatever password you like
    #         MYSQL_PASSWORD: 'admin1'
    #         # Password for root access
    #         MYSQL_ROOT_PASSWORD: 'admin1'
    #     volumes:
    #         - ./mysql-dump:/docker-entrypoint-initdb.d
    #         - ./db:/var/lib/mysql
    #     ports:
    #         - "3306:3306"
    #     expose:
    #         - "3306"

    backend:
        build: ./backend
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - ./backend:/app
            - ./db:/db
        ports:
            - "5000:5000"


    db_update_service:
        build: ./db_update_service
        environment:
          PYTHONUNBUFFERED: 1
        volumes:
          - ./db_update_service:/app
        depends_on:
          - backend
