version: "3.7"

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'adrian'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin1'
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

  backend:
    build: ./backend
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
