version: "3.7"

services:

    backend:
        build: ./backend
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - ./backend:/app
            - ./db:/db
        ports:
            - "5000:5000"


    db_update_service:
        build: ./db_update_service
        environment:
          PYTHONUNBUFFERED: 1
        volumes:
          - ./db_update_service:/app
        depends_on:
          - backend

    frontend:
        build: ./frontend
        command: npm run serve -- --port 80
        volumes:
            - ./frontend:/frontend
        
        environment: 
            - VUE_APP_URL=http://localhost:5000 
        depends_on:
            - backend
        network_mode: host

